# Generated by Django 2.2.16 on 2021-12-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211201_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followed',
        ),
    ]
