# Generated by Django 2.2.16 on 2021-12-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211201_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='author',
        ),
    ]
